spring:
  application:
    name: agent

server:
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: '*'
    tags:
      application: ${spring.application.name}
logging:
  level:
    root: INFO
#  pattern: